//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.27 at 11:04:30 AM CDT 
//


package com.dextratech.dtf.xml.testsuite;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for actionOption complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="actionOption">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice maxOccurs="unbounded" minOccurs="0">
 *           &lt;element name="field" type="{http://www.dextratech.com/testsuite}field" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;element name="action" type="{http://www.dextratech.com/testsuite}action" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;element name="assert" type="{http://www.dextratech.com/testsuite}assertion" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;element name="custom" type="{http://www.dextratech.com/testsuite}genericCommand" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;element name="include" type="{http://www.dextratech.com/testsuite}include" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;element name="onload" type="{http://www.dextratech.com/testsuite}onload" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;element name="captureScreenshot" type="{http://www.dextratech.com/testsuite}captureScreenshot" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "actionOption", propOrder = {
    "fieldOrActionOrAssert"
})
@XmlSeeAlso({
    Component.class,
    Testcase.class
})
public class ActionOption {

    @XmlElements({
        @XmlElement(name = "custom", type = GenericCommand.class),
        @XmlElement(name = "include", type = Include.class),
        @XmlElement(name = "onload", type = Onload.class),
        @XmlElement(name = "field", type = Field.class),
        @XmlElement(name = "action", type = Action.class),
        @XmlElement(name = "captureScreenshot", type = CaptureScreenshot.class),
        @XmlElement(name = "assert", type = Assertion.class)
    })
    protected List<Object> fieldOrActionOrAssert;

    /**
     * Gets the value of the fieldOrActionOrAssert property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the fieldOrActionOrAssert property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFieldOrActionOrAssert().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link GenericCommand }
     * {@link Include }
     * {@link Onload }
     * {@link Field }
     * {@link Action }
     * {@link CaptureScreenshot }
     * {@link Assertion }
     * 
     * 
     */
    public List<Object> getFieldOrActionOrAssert() {
        if (fieldOrActionOrAssert == null) {
            fieldOrActionOrAssert = new ArrayList<Object>();
        }
        return this.fieldOrActionOrAssert;
    }

}
