//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.27 at 11:04:30 AM CDT 
//


package com.dextratech.dtf.xml.testsuite;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for action complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="action">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="actionType" type="{http://www.dextratech.com/testsuite}seleneseCommand" />
 *       &lt;attribute name="locatorType" type="{http://www.dextratech.com/testsuite}locatorType" default="id" />
 *       &lt;attribute name="locatorValue" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="additionalParameter" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="errorStep" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "action")
public class Action {

    @XmlAttribute
    protected SeleneseCommand actionType;
    @XmlAttribute
    protected LocatorType locatorType;
    @XmlAttribute
    protected String locatorValue;
    @XmlAttribute
    protected String additionalParameter;
    @XmlAttribute
    protected Boolean errorStep;

    /**
     * Gets the value of the actionType property.
     * 
     * @return
     *     possible object is
     *     {@link SeleneseCommand }
     *     
     */
    public SeleneseCommand getActionType() {
        return actionType;
    }

    /**
     * Sets the value of the actionType property.
     * 
     * @param value
     *     allowed object is
     *     {@link SeleneseCommand }
     *     
     */
    public void setActionType(SeleneseCommand value) {
        this.actionType = value;
    }

    /**
     * Gets the value of the locatorType property.
     * 
     * @return
     *     possible object is
     *     {@link LocatorType }
     *     
     */
    public LocatorType getLocatorType() {
        if (locatorType == null) {
            return LocatorType.ID;
        } else {
            return locatorType;
        }
    }

    /**
     * Sets the value of the locatorType property.
     * 
     * @param value
     *     allowed object is
     *     {@link LocatorType }
     *     
     */
    public void setLocatorType(LocatorType value) {
        this.locatorType = value;
    }

    /**
     * Gets the value of the locatorValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocatorValue() {
        return locatorValue;
    }

    /**
     * Sets the value of the locatorValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocatorValue(String value) {
        this.locatorValue = value;
    }

    /**
     * Gets the value of the additionalParameter property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdditionalParameter() {
        return additionalParameter;
    }

    /**
     * Sets the value of the additionalParameter property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdditionalParameter(String value) {
        this.additionalParameter = value;
    }

    /**
     * Gets the value of the errorStep property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isErrorStep() {
        if (errorStep == null) {
            return false;
        } else {
            return errorStep;
        }
    }

    /**
     * Sets the value of the errorStep property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setErrorStep(Boolean value) {
        this.errorStep = value;
    }

}
