//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.27 at 11:04:30 AM CDT 
//


package com.dextratech.dtf.xml.testsuite;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for field complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="field">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="validValueDef" type="{http://www.dextratech.com/testsuite}validFieldValue" minOccurs="0"/>
 *         &lt;choice maxOccurs="unbounded" minOccurs="0">
 *           &lt;element name="validate" type="{http://www.dextratech.com/testsuite}validation" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;element name="validateFunction" type="{http://www.dextratech.com/testsuite}validationFunction" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;element name="validateFunctionRef" type="{http://www.dextratech.com/testsuite}validationFunctionRef" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *       &lt;attribute name="name" use="required" type="{http://www.dextratech.com/testsuite}elementName" />
 *       &lt;attribute name="locatorType" type="{http://www.dextratech.com/testsuite}locatorType" default="id" />
 *       &lt;attribute name="locatorValue" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="validValue">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;minLength value="0"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="errorStep" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "field", propOrder = {
    "validValueDef",
    "validateOrValidateFunctionOrValidateFunctionRef"
})
public class Field {

    protected ValidFieldValue validValueDef;
    @XmlElements({
        @XmlElement(name = "validate", type = Validation.class),
        @XmlElement(name = "validateFunction", type = ValidationFunction.class),
        @XmlElement(name = "validateFunctionRef", type = ValidationFunctionRef.class)
    })
    protected List<Object> validateOrValidateFunctionOrValidateFunctionRef;
    @XmlAttribute(required = true)
    protected String name;
    @XmlAttribute
    protected LocatorType locatorType;
    @XmlAttribute
    protected String locatorValue;
    @XmlAttribute
    protected String validValue;
    @XmlAttribute
    protected Boolean errorStep;

    /**
     * Gets the value of the validValueDef property.
     * 
     * @return
     *     possible object is
     *     {@link ValidFieldValue }
     *     
     */
    public ValidFieldValue getValidValueDef() {
        return validValueDef;
    }

    /**
     * Sets the value of the validValueDef property.
     * 
     * @param value
     *     allowed object is
     *     {@link ValidFieldValue }
     *     
     */
    public void setValidValueDef(ValidFieldValue value) {
        this.validValueDef = value;
    }

    /**
     * Gets the value of the validateOrValidateFunctionOrValidateFunctionRef property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the validateOrValidateFunctionOrValidateFunctionRef property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getValidateOrValidateFunctionOrValidateFunctionRef().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Validation }
     * {@link ValidationFunction }
     * {@link ValidationFunctionRef }
     * 
     * 
     */
    public List<Object> getValidateOrValidateFunctionOrValidateFunctionRef() {
        if (validateOrValidateFunctionOrValidateFunctionRef == null) {
            validateOrValidateFunctionOrValidateFunctionRef = new ArrayList<Object>();
        }
        return this.validateOrValidateFunctionOrValidateFunctionRef;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the locatorType property.
     * 
     * @return
     *     possible object is
     *     {@link LocatorType }
     *     
     */
    public LocatorType getLocatorType() {
        if (locatorType == null) {
            return LocatorType.ID;
        } else {
            return locatorType;
        }
    }

    /**
     * Sets the value of the locatorType property.
     * 
     * @param value
     *     allowed object is
     *     {@link LocatorType }
     *     
     */
    public void setLocatorType(LocatorType value) {
        this.locatorType = value;
    }

    /**
     * Gets the value of the locatorValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocatorValue() {
        return locatorValue;
    }

    /**
     * Sets the value of the locatorValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocatorValue(String value) {
        this.locatorValue = value;
    }

    /**
     * Gets the value of the validValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValidValue() {
        return validValue;
    }

    /**
     * Sets the value of the validValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValidValue(String value) {
        this.validValue = value;
    }

    /**
     * Gets the value of the errorStep property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isErrorStep() {
        if (errorStep == null) {
            return false;
        } else {
            return errorStep;
        }
    }

    /**
     * Sets the value of the errorStep property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setErrorStep(Boolean value) {
        this.errorStep = value;
    }

}
