//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.27 at 11:04:30 AM CDT 
//


package com.dextratech.dtf.xml.testsuite;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for testcase complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="testcase">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.dextratech.com/testsuite}actionOption">
 *       &lt;sequence>
 *         &lt;element name="afterErrorActions" type="{http://www.dextratech.com/testsuite}actionOption" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" type="{http://www.dextratech.com/testsuite}elementName" />
 *       &lt;attribute name="url" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="success" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="run" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *       &lt;attribute name="runDefault" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *       &lt;attribute name="defaultAssert" type="{http://www.dextratech.com/testsuite}elementName" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "testcase", propOrder = {
    "afterErrorActions"
})
public class Testcase
    extends ActionOption
{

    protected ActionOption afterErrorActions;
    @XmlAttribute
    protected String name;
    @XmlAttribute
    protected String url;
    @XmlAttribute
    protected Boolean success;
    @XmlAttribute
    protected Boolean run;
    @XmlAttribute
    protected Boolean runDefault;
    @XmlAttribute
    protected String defaultAssert;

    /**
     * Gets the value of the afterErrorActions property.
     * 
     * @return
     *     possible object is
     *     {@link ActionOption }
     *     
     */
    public ActionOption getAfterErrorActions() {
        return afterErrorActions;
    }

    /**
     * Sets the value of the afterErrorActions property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActionOption }
     *     
     */
    public void setAfterErrorActions(ActionOption value) {
        this.afterErrorActions = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the url property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUrl() {
        return url;
    }

    /**
     * Sets the value of the url property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUrl(String value) {
        this.url = value;
    }

    /**
     * Gets the value of the success property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isSuccess() {
        return success;
    }

    /**
     * Sets the value of the success property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSuccess(Boolean value) {
        this.success = value;
    }

    /**
     * Gets the value of the run property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isRun() {
        if (run == null) {
            return true;
        } else {
            return run;
        }
    }

    /**
     * Sets the value of the run property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRun(Boolean value) {
        this.run = value;
    }

    /**
     * Gets the value of the runDefault property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isRunDefault() {
        if (runDefault == null) {
            return true;
        } else {
            return runDefault;
        }
    }

    /**
     * Sets the value of the runDefault property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRunDefault(Boolean value) {
        this.runDefault = value;
    }

    /**
     * Gets the value of the defaultAssert property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefaultAssert() {
        return defaultAssert;
    }

    /**
     * Sets the value of the defaultAssert property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefaultAssert(String value) {
        this.defaultAssert = value;
    }

}
